sources:
  - name: bronze
    schema: bronze
    tables:
      - name: listings
      - name: bookings
      - name: hosts

models:
  - name: silver_bookings
    columns:
      - name: booking_id
        tests:
          - unique
          - not_null

      - name: total_revenue
        tests:
          - not_null

  - name: silver_hosts
    columns:
      - name: host_id
        tests:
          - unique
          - not_null